language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tal51198/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tal51198/docker-react npm run test -- --coverage
